name: release-build

on:
  push:
    branches:
      - main

jobs:
  build-win64:
    runs-on: windows-latest
    env:
      OS: windows
    steps:
      - uses: actions/checkout@v2
      - name: Setup GralLVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install native-image
        run: ${{ env.JAVA_HOME }}\bin\gu.cmd install native-image
        shell: cmd
      - name: Configure Pagefile
        # Increased the page-file size due to memory-consumption of native-image command
        # For details see https://github.com/actions/virtual-environments/issues/785
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Build native executable
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          ./gradlew build -Dquarkus.package.type=native
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: rpr-logger-1-runner.exe
          path: /**/rpr-logger-1-runner.exe